apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-tracker-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/charanghanta12/Fitness_Tracker.git'
    targetRevision: staging
    path: Fitness_Chart
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fitness-tracker-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
